# Generated by Django 4.2.5 on 2023-09-17 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate_of_violations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Control_action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employ_position_act',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employ_position_contr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Method',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_oper', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_proc', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reestr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('control_action', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fk_app.control_action')),
                ('employ_actint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fk_app.employ_position_act')),
                ('employ_contr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fk_app.employ_position_contr')),
                ('method', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fk_app.method')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fk_app.operation')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('employ_position_contr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fk_app.employ_position_contr')),
            ],
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=256)),
                ('amount', models.FloatField(max_length=256)),
                ('certificate_of_violations', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fk_app.certificate_of_violations')),
                ('employ_position_contr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fk_app.employ_position_contr')),
                ('reestr', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fk_app.reestr')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fk_app.worker')),
            ],
        ),
        migrations.AddField(
            model_name='operation',
            name='process',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fk_app.process'),
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('measures', models.TextField(max_length=256)),
                ('violation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fk_app.violation')),
            ],
        ),
        migrations.AddField(
            model_name='certificate_of_violations',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fk_app.worker'),
        ),
    ]
