# Generated by Django 4.2.5 on 2023-09-20 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fk_app', '0002_employ_position_remove_worker_employ_position_contr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='violation',
            name='employ_position_contr',
        ),
        migrations.AddField(
            model_name='violation',
            name='employ_position_act',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fk_app.employ_position_act'),
            preserve_default=False,
        ),
    ]
